server:
  port: ${PORT:80}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0